export interface StockKoreanModel {
  // stk_cd: string; // 종목코드
  // stk_nm: string; // 종목명
  // setl_mm: string; // 결산월
  // fav: string; // 액면가
  // cap: string; // 자본금
  // flo_stk: string; // 상장주식
  // crd_rt: string; // 신용비율
  // oyr_hgst: string; // 연중최고
  // oyr_lwst: string; // 연중최저
  // mac: string; // 시가총액
  // mac_wght: string; // 시가총액비중
  // for_exh_rt: string; // 외인소진률
  // repl_pric: string; // 대용가
  // per: string; // PER
  // eps: string; // EPS
  // roe: string; // ROE
  // pbr: string; // PBR
  // ev: string; // EV
  // bps: string; // BPS
  // sale_amt: string; // 매출액
  // bus_pro: string; // 영업이익
  // cup_nga: string; // 당기순이익
  // '250hgst': string; // 250최고
  // '250lwst': string; // 250최저
  // high_pric: string; // 고가
  // open_pric: string; // 시가
  // low_pric: string; // 저가
  // upl_pric: string; // 상한가
  // lst_pric: string; // 하한가
  // base_pric: string; // 기준가
  // exp_cntr_pric: string; // 예상체결가
  // exp_cntr_qty: string; // 예상체결수량
  // '250hgst_pric_dt': string; // 250최고가일
  // '250hgst_pric_pre_rt': string; // 250최고가대비율
  // '250lwst_pric_dt': string; // 250최저가일
  // '250lwst_pric_pre_rt': string; // 250최저가대비율
  // cur_prc: string; // 현재가
  // pre_sig: string; // 대비기호
  // pred_pre: string; // 전일대비
  // flu_rt: string; // 등락율
  // trde_qty: string; // 거래량
  // trde_pre: string; // 거래대비
  // fav_unit: string; // 액면가단위
  // dstr_stk: string; // 유통주식
  // dstr_rt: string; // 유통비율
}
