import { GoogleAnalytics } from '@next/third-parties/google';
import type { Metadata } from 'next';

import { Modal, Toast } from '@/components/modal';

import { NetworkError } from '@/lib/network-error';
import QueryProvider from '@/lib/react-query/react-query.config';

import './globals.css';

export const metadata: Metadata = {
  title: 'peek',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <NetworkError>
          <QueryProvider>
            {/*<MessagingConfig>*/}
            {children}
            {/*</MessagingConfig>*/}
          </QueryProvider>
        </NetworkError>

        <Modal />
        <Toast />

        <div id="modal-root" />
        <div id="toast-root" />
      </body>

      <GoogleAnalytics gaId={String(process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS)} />
    </html>
  );
}
