import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import QueryProvider from '@/common/react-query/reactQuery.config';

import Modal from '@/components/modal/modal';
import Toast from '@/components/modal/toast';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'peek',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <QueryProvider>
          {/*<MessagingConfig>*/}
          {children}
          <Modal />
          <Toast />
          {/*</MessagingConfig>*/}
        </QueryProvider>
        <div id="modal-root" />
        <div id="toast-root" />
      </body>
    </html>
  );
}
