export * from './alertSvg';
export * from './backSvg';
export * from './boardRegisterSvg';
export * from './checkBoxSvg';
export * from './commentSvg';
export * from './confirmSvg';
export * from './deleteSvg';
export * from './humanSvg';
export * from './humanSvg';
